// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdprC0NkEXgP9nyoX2BdAHMj2zt7KseC0',
    appId: '1:195349302325:web:c3e5d0301020db00fe757c',
    messagingSenderId: '195349302325',
    projectId: 'cater-ease',
    authDomain: 'cater-ease.firebaseapp.com',
    storageBucket: 'cater-ease.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGmXoX1z9SOl_uQF9hraBDQTJSc7A3g9k',
    appId: '1:195349302325:android:737308df98c0500afe757c',
    messagingSenderId: '195349302325',
    projectId: 'cater-ease',
    storageBucket: 'cater-ease.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1rrB3_nofkDdJc7odaTMK75deH0sLfgo',
    appId: '1:195349302325:ios:31c0af6267debd94fe757c',
    messagingSenderId: '195349302325',
    projectId: 'cater-ease',
    storageBucket: 'cater-ease.appspot.com',
    iosClientId: '195349302325-2reh4lfhrn61u9f7h00a4ie1og9hsr8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.caterEase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1rrB3_nofkDdJc7odaTMK75deH0sLfgo',
    appId: '1:195349302325:ios:31c0af6267debd94fe757c',
    messagingSenderId: '195349302325',
    projectId: 'cater-ease',
    storageBucket: 'cater-ease.appspot.com',
    iosClientId: '195349302325-2reh4lfhrn61u9f7h00a4ie1og9hsr8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.caterEase',
  );
}
